name: Feature request
description: "💡 Suggest an idea for this project"
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you do like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Anything else?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshot about the feature request here.
    validations:
      required: false
