name: build-cli-linux-aarch64-appimage-testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@v6
      with:
        repository: ctlcltd/e2-sat-editor
        path: e2-sat-editor

    - name: Setup Aptitude
      run: |
        sudo apt-get update
        sudo apt-get install wget
        sudo apt-get install cmake ninja-build

    - name: Download deploy tools
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage
        wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-aarch64.AppImage
        chmod +x linuxdeploy-aarch64.AppImage
        chmod +x appimagetool-aarch64.AppImage
        mv linuxdeploy-aarch64.AppImage /usr/local/bin/linuxdeploy
        mv appimagetool-aarch64.AppImage /usr/local/bin/appimagetool

    - name: Configure CMake
      working-directory: ${{github.workspace}}/e2-sat-editor/src/cli
      run: |
        cmake \
        -G Ninja \
        -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
        -DRELEASE_MEDIUM=github

    - name: Build
      working-directory: ${{github.workspace}}/e2-sat-editor/src/cli
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Deploy artifact
      working-directory: ${{github.workspace}}/e2-sat-editor/src/cli
      continue-on-error: true
      run: |
        DESTDIR=../AppDir ninja -C build install
        # usr-share
        mkdir -p AppDir/usr/share/{applications,metainfo}
        cp AppDir/usr/share/applications/e2se-cli.desktop AppDir/usr/share/applications/io.github.ctlcltd.e2se-cli.desktop
        cp AppDir/usr/share/metainfo/io.github.ctlcltd.e2se-cli.metainfo.xml AppDir/usr/share/metainfo/io.github.ctlcltd.e2se-cli.appdata.xml
        mkdir -p AppDir/usr/share/doc/e2se-cli
        mv AppDir/usr/share/e2se-cli/Readme.txt AppDir/usr/share/doc/e2se-cli/readme
        mv AppDir/usr/share/e2se-cli/License.txt AppDir/usr/share/doc/e2se-cli/copyright
        mv AppDir/usr/share/e2se-cli/Third-Party.txt AppDir/usr/share/doc/e2se-cli/third-party
        # run linuxdeploy
        linuxdeploy --appdir AppDir --output appimage
        # package
        mv e2se-cli-aarch64.AppImage ../../artifact

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        path: ${{github.workspace}}/e2-sat-editor/artifact
